name: Coverage-Monitor
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install npm
        run: npm install

      - name: Test
        run: npx jest --coverage

      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "./coverage/clover.xml"
          threshold_alert: 70
          threshold_warning: 80
